/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BeneficiarioPresentacion;

import DTOs.BeneficiarioDTO;
import DTOs.CuentaBancariaDTO;
import excepcion.ExcepcionPresentacion;
import excepcionBO.ExcepcionBO;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.PagoBO;

/**
 *
 * @author diana
 */
public class ModificarCuenta extends javax.swing.JFrame {
    PagoBO pagoBO;
    long id;
    
    /**
     * Creates new form ModificarCuenta
     */
    public ModificarCuenta(PagoBO pagoBO, long id) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setSize(965, 610);
        this.pagoBO=pagoBO;
        this.id=id;
        
        cargarTextos();
    }
    
    public void cargarTextos(){
        try {
            CuentaBancariaDTO cuenta=pagoBO.buscarCuentaBancariaPorId(id);
            textoNumero.setText(cuenta.getNumeroCuenta());
            textoClabe.setText(cuenta.getClave());
            textoBanco.setText(cuenta.getBanco());
        } catch (ExcepcionBO ex) {
            try {
                throw new ExcepcionPresentacion(ex.getMessage());
            } catch (ExcepcionPresentacion ex1) {
                Logger.getLogger(ModificarCuenta.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbono = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRegresar3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textoNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoClabe = new javax.swing.JTextField();
        btnAbono1 = new javax.swing.JButton();
        textoBanco = new javax.swing.JTextField();

        btnAbono.setText("Agregar Abono");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(175, 176, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnRegresar3.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar3.setText("←");
        btnRegresar3.setContentAreaFilled(false);
        btnRegresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar Cuenta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));
        jPanel1.add(textoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 270, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Clabe");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Banco");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. Cuenta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));
        jPanel1.add(textoClabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 270, 30));

        btnAbono1.setBackground(new java.awt.Color(116, 114, 178));
        btnAbono1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        btnAbono1.setForeground(new java.awt.Color(255, 255, 255));
        btnAbono1.setText("Modificar Cuenta");
        btnAbono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbono1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 140, 30));
        jPanel1.add(textoBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar3ActionPerformed
        // TODO add your handling code here:
        MisCuentasBancarias misCuentasBancarias = new MisCuentasBancarias(pagoBO);
        misCuentasBancarias.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar3ActionPerformed

    private void btnAbono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbono1ActionPerformed
         try {
            CuentaBancariaDTO cuenta = pagoBO.buscarCuentaBancariaPorId(id);

            if (cuenta != null) {
                cuenta.setNumeroCuenta(textoNumero.getText());
                cuenta.setClave(textoClabe.getText());
                cuenta.setBanco(textoBanco.getText());
                cuenta.setEliminada(false);

                BeneficiarioDTO beneficiario = cuenta.getBeneficiario();
                if (beneficiario != null) {
                    System.out.println("ID del beneficiario asociado: " + beneficiario.getId());
                    pagoBO.actualizarCuentaBancaria(cuenta);
                    MisCuentasBancarias cuentas=new MisCuentasBancarias(pagoBO);
                    cuentas.show();
                    this.dispose();
                } else {
                   
                    System.out.println("El beneficiario asociado a la cuenta es nulo.");
                }
            } else {
                System.out.println("La cuenta bancaria no se encontró para el ID proporcionado: " + id);
            }
        } catch (ExcepcionBO ex) {
            try {
                throw new ExcepcionPresentacion(ex.getMessage());
            } catch (ExcepcionPresentacion ex1) {
                Logger.getLogger(ModificarCuenta.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_btnAbono1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbono;
    private javax.swing.JButton btnAbono1;
    private javax.swing.JButton btnRegresar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textoBanco;
    private javax.swing.JTextField textoClabe;
    private javax.swing.JTextField textoNumero;
    // End of variables declaration//GEN-END:variables
}
